### ISSUE TITLE
Bug in PACToolbox - EEGLAB plugin

### ISSUE THREAD

**Issue by arnodelorme** [sccn/PACT#1]
From https://sccn.ucsd.edu/bugzilla/show_bug.cgi?id=1868

Dear All,

While working with an EDF+ file in EEGLAB, I found a bug when attempting to perform PAC using the PACToolbox. The error is:

"Error using cell/unique (line 95)
Input A must be a cell array of strings.

Error in pac_pop_main (line 60)
    eventTypes = unique({EEG.event.type});
 
Error while evaluating uimenu Callback"

The data has 32768 frames per epoch (1 epoch of 16s) and a sampling rate of 2048Hz. I tried working with sets of data of shorter time frames but then it gave an error when performing an initial step of band pass filtering using FIR (lower edge - 0.5Hz and higher edge - 600Hz): "epoch frames must be at least 3 times the filter order. (error occurred in function eegfilt() at line 132)".

So far couldn't find any info on this. Any insight would be much appreciated.

Bárbara

**Comment by MakotoMiyakoshi** [comment]
This error report is from April 2016, more than three and a half year old. As Ramon answered in the original Bugzilla 5 hours after receiving the report (quick!), this could be due to missing event problem after importing EDF file. Another possibility is that EEG.event.type is not strings but numbers. In this case, EEG.event.type needs to be converted into strings. I thought eeg_checkset() or some EEGLAB check function takes care of this problem now... (or was it related to creating STUDY?)

**Comment by arnodelorme** [comment]
OK, I am closing the report then.

**Comment by MakotoMiyakoshi** [comment]
Thanks.
